print corresponding kernel filename
Signed-off-by: Leslie Qi Wang <leslie.qiwa@gmail.com>

diff --git a/lib/novm/libexec/extract-vmlinux b/lib/novm/libexec/extract-vmlinux
--- a/lib/novm/libexec/extract-vmlinux
+++ b/lib/novm/libexec/extract-vmlinux
@@ -59,4 +59,4 @@ try_decompress '\135\0\0\0'   xxx   unlzma
 try_decompress '\211\114\132' xy    'lzop -d'
 
 # Bail out:
-echo "$me: Cannot find vmlinux." >&2
+echo "$me: Cannot find vmlinux: $img" >&2
